language: node_js
node_js:
  - 13

services:
  - docker  

# safelist
branches:
  only:
  - master
# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build

script: 
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy  ./udagram-reverseproxy
  # Do similar for other three images

  #Tagging
  - docker tag udagram-api-feed edexy/udagram-api-feed:v1
  - docker tag udagram-api-user edexy/udagram-api-user:v1
  - docker tag udagram-frontend edexy/udagram-frontend:v1
  - docker tag reverseproxy edexy/reverseproxy:v1
  # Do similar for other three images

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push edexy/udagram-api-feed:v1
  - docker push edexy/udagram-api-user:v1
  - docker push edexy/udagram-frontend:v1
  - docker push edexy/reverseproxy:v1
  # Do similar for other three images